var MENU = {

    bolos: [
        {
          id: "classic-vanilla-cake",
          img: "./img/cardapio/bolos/bolo1.avif",
          name: "Delight Bakery",
          dsc: "Classic Vanilla Cake with Buttercream Frosting",
          price: 39,
        },
        {
          id: "chocolate-heaven-cake",
          img: "./img/cardapio/bolos/bolo2.avif",
          name: "Sweet Treats",
          dsc: "Rich Chocolate Heaven Cake - 8 Slices",
          price: 45,
        },
        {
          id: "red-velvet-cake",
          img: "./img/cardapio/bolos/bolo3.avif",
          name: "Velvet Delights",
          dsc: "Red Velvet Cake with Cream Cheese Frosting",
          price: 49,
        },
        {
          id: "strawberry-shortcake",
          img: "./img/cardapio/bolos/bolo4.avif",
          name: "Berry Bliss",
          dsc: "Strawberry Shortcake - 6 Slices",
          price: 42,
        },
        {
          id: "lemon-drizzle-cake",
          img: "./img/cardapio/bolos/bolo5.avif",
          name: "Zesty Bakes",
          dsc: "Tangy Lemon Drizzle Cake",
          price: 35,
        },
        {
          id: "carrot-cake",
          img: "./img/cardapio/bolos/bolo6.avif",
          name: "Harvest Delights",
          dsc: "Classic Carrot Cake with Walnuts and Cream Frosting",
          price: 39,
        },
        {
          id: "black-forest-cake",
          img: "./img/cardapio/bolos/bolo1.avif",
          name: "Choco-Cherry Bliss",
          dsc: "Black Forest Cake with Cherries and Whipped Cream",
          price: 55,
        },
        {
          id: "rainbow-layer-cake",
          img: "./img/cardapio/bolos/bolo2.avif",
          name: "Rainbow Joy",
          dsc: "Colorful Rainbow Layer Cake - 8 Slices",
          price: 59,
        },
        {
          id: "coconut-dream-cake",
          img: "./img/cardapio/bolos/bolo3.avif",
          name: "Island Flavors",
          dsc: "Coconut Dream Cake with Tropical Flavors",
          price: 48,
        },
        {
          id: "chiffon-cake",
          img: "./img/cardapio/bolos/bolo4.avif",
          name: "Airy Delights",
          dsc: "Light and Fluffy Chiffon Cake",
          price: 37,
        },
        {
          id: "coffee-walnut-cake",
          img: "./img/cardapio/bolos/bolo5.avif",
          name: "Morning Bliss",
          dsc: "Coffee and Walnut Cake - Perfect for Brunch",
          price: 44,
        },
        {
          id: "matcha-green-tea-cake",
          img: "./img/cardapio/bolos/bolo6.avif",
          name: "Green Harmony",
          dsc: "Matcha Green Tea Cake with White Chocolate Frosting",
          price: 53,
        },
      ],
  doces: [
    {
      id: "15259-german-chocolate-killer-brownie-tin-pack",
      img: "./img/cardapio/sobremesas/german-chocolate-killer-brownie-tin-pack.5ebc34160f28767a9d94c4da2e04c4b9.jpg",
      name: "Killer Brownie®",
      dsc: "German Chocolate Killer Brownie®",
      price: 39.99,
    },
    {
      id: "jacques-world-famous-chocolate-chip-cookies",
      img: "./img/cardapio/sobremesas/jacques-world-famous-chocolate-chip-cookies-6-pack.2217a14c443602493bba88aa9335319a.jpg",
      name: "Jacques Torres Chocolate",
      dsc: "Jacques' World Famous Chocolate Chip Cookies - 6 Pack",
      price: 39.95,
    },
    {
      id: "luigis-original-cannoli-pie",
      img: "./img/cardapio/sobremesas/original-cannoli-pie.4cb5b9ba82f57b69b90765fd9f07aa1a.jpg",
      name: "The Cannoli Pie Company",
      dsc: "Original Cannoli Pie",
      price: 69,
    },
    {
      id: "sea-salted-caramel-swirl-cheesecake",
      img: "./img/cardapio/sobremesas/sea-salted-caramel-swirl-cheesecake.e2825335433fb7a272a5d77649a6849e.jpg",
      name: "Cotton Blues Cheesecake Company",
      dsc: "Sea-Salted Caramel Swirl Cheesecake",
      price: 65,
    },
    {
      id: "brooklyn-blackout-cookie-brownie-combo-pack-2-tins",
      img: "./img/cardapio/sobremesas/brooklyn-blackout-cookie-brownie-combo-pack-2-tins.d8805325baf6b23b4f01d119dc4531a7.jpg",
      name: "Brooklyn Blackout Company",
      dsc: "Brooklyn Blackout Cookie + Brownie Combo Pack - 2 Tins",
      price: 89,
    },
    {
      id: "best-seller-cupcake-dozen",
      img: "./img/cardapio/sobremesas/best-seller-cupcake-dozen.f93b21993f6a2da11c975d45b9b0d08f.jpg",
      name: "Crave Cupcakes",
      dsc: "Best Seller Cupcake Dozen",
      price: 89,
    },
    {
      id: "choose-your-own-ice-cream-donuts-6-pack",
      img: "./img/cardapio/sobremesas/choose-your-own-ice-cream-donuts-6-pack.24d0b44765a7c54237fcd7ea9d9d8093.jpg",
      name: "Elegant Desserts",
      dsc: "Choose Your Own Ice Cream Donuts - 6 Pack",
      price: 69,
    },
    {
      id: "17481-jewish-dessert-3-pack",
      img: "./img/cardapio/sobremesas/jewish-classics-dessert-pack.7d4b76630f2fe75dcb7bbcf2501b7390.jpg",
      name: "Ess-a-Bagel",
      dsc: "Jewish Classics Dessert Pack",
      price: 89.95,
    },
    {
      id: "dessert-bar-care-package",
      img: "./img/cardapio/sobremesas/dessert-bar-care-package.324aa28fe98c9dc67b75aac43376902e.jpg",
      name: "Bread and Roses Bakery",
      dsc: "Dessert Bar Care Package",
      price: 65,
    },
    {
      id: "donut-cookies-12-pack",
      img: "./img/cardapio/sobremesas/donut-cookies-12-pack.46f42c61c4a79fd2051a99b2f23e890e.jpg",
      name: "Stan's Donuts",
      dsc: "Donut Cookies - 12 Pack",
      price: 49,
    },
    {
      id: "gulab-jamun-ice-cream-cakes-2-pack",
      img: "./img/cardapio/sobremesas/gulab-jamun-ice-cream-cakes-2-pack.c45b4d0750ad22d741f84dc1f26d20e7.jpg",
      name: "Malai Ice Cream",
      dsc: "Gulab Jamun Ice Cream Cakes - 2 Pack",
      price: 79,
    },
    {
      id: "jacques-world-famous-chocolate-chip-cookies-12-pack",
      img: "./img/cardapio/sobremesas/jacques-world-famous-chocolate-chip-cookies-12-pack.3b373bdd67cd25084182c21499f675d1.jpg",
      name: "Jacques Torres Chocolate",
      dsc: "Jacques' World Famous Chocolate Chip Cookies - 12 Pack",
      price: 69.95,
    },
  ],
};
